name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  test-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies & Run Tests
        run: |
          pip install -r requirements.txt
          pip install pytest
          pytest tests/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.girish9851 }}
          password: ${{ secrets.Mintoo@9867 }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: girish9851/agent-app:latest
     - name: Install Locust and Run Load Test
        run: |
          pip install locust
          locust -f locustfile.py --headless -u 20 -r 5 -t 30s --host http://localhost:8000
